#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ListviewButton.Resource", IsApplication=true)]

namespace ListviewButton
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Chicken = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Chinchilla = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Donkey = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Duck = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Elephant = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Giraffe = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Hawk = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Lion = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Lobster = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Penguin = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Pig = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Rabbit = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Rhino = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Skunk = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Squirrel = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Turtle = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Walrus = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Zebra = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int btn_Take = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int imageItem = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int linearText = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int myButton = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int textBottom = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int textTop = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int widget28 = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AnimalItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
